// Create a JavaScript object where the keys are the two letter country codes 
// for every country and the values are the name of the country in lowercase 
// with spaces replaced by hyphens
const countryCodes = {
    "ad": "andorra",
    "ae": "united-arab-emirates",
    "af": "afghanistan",
    "ag": "antigua-and-barbuda",
    "ai": "anguilla",
    "al": "albania",
    "am": "armenia",
    "ao": "angola",
    "aq": "antarctica",
    "ar": "argentina",
    "as": "american-samoa",
    "at": "austria",
    "au": "australia",
    "aw": "aruba",
    "ax": "aland",
    "az": "azerbaijan",
    "ba": "bosnia-and-herzegovina",
    "bb": "barbados",
    "bd": "bangladesh",
    "be": "belgium",
    "bf": "burkina-faso",
    "bg": "bulgaria",
    "bh": "bahrain",
    "bi": "burundi",
    "bj": "benin",
    "bl": "saint-barthelemy",
    "bm": "bermuda",
    "bn": "brunei",
    "bo": "bolivia",
    "bq": "bonaire",
    "br": "brazil",
    "bs": "bahamas",
    "bt": "bhutan",
    "bw": "botswana",
    "by": "belarus",
    "bz": "belize",
    "ca": "canada",
    "cc": "cocos-islands",
    "cd": "congo-kinshasa",
    "cf": "central-african-republic",
    "cg": "congo-brazzaville",
    "ch": "switzerland",
    "ci": "cote-divoire",
    "ck": "cook-islands",
    "cl": "chile",
    "cm": "cameroon",
    "cn": "china",
    "co": "colombia",
    "cr": "costa-rica",
    "cu": "cuba",
    "cv": "cape-verde",
    "cw": "curacao",
    "cx": "christmas-island",
    "cy": "cyprus",
    "cz": "czechia",
    "de": "germany",
    "dj": "djibouti",
    "dk": "denmark",
    "dm": "dominica",
    "do": "dominican-republic",
    "dz": "algeria",
    "ec": "ecuador",
    "ee": "estonia",
    "eg": "egypt",
    "eh": "western-sahara",
    "er": "eritrea",
    "es": "spain",
    "et": "ethiopia",
    "fi": "finland",
    "fj": "fiji",
    "fk": "falklands",
    "fm": "micronesia",
    "fo": "faroe-islands",
    "fr": "france",
    "ga": "gabon",
    "gb": "united-kingdom",
    "gd": "grenada",
    "ge": "georgia",
    "gf": "french-guiana",
    "gg": "guernsey",
    "gh": "ghana",
    "gi": "gibraltar",
    "gl": "greenland",
    "gm": "gambia",
    "gn": "guinea",
    "gp": "guadeloupe",
    "gq": "equatorial-guinea",
    "gr": "greece",
    "gs": "south-georgia",
    "gt": "guatemala",
    "gu": "guam",
    "gw": "guinea-bissau",
    "gy": "guyana",
    "hk": "hong-kong",
    "hm": "heard-island-and-mcdonald-islands",
    "hn": "honduras",
    "hr": "croatia",
    "ht": "haiti",
    "hu": "hungary",
    "id": "indonesia",
    "ie": "ireland",
    "il": "israel",
    "im": "isle-of-man",
    "in": "india",
    "io": "british-indian-ocean-territory",
    "iq": "iraq",
    "ir": "iran",
    "is": "iceland",
    "it": "italy",
    "je": "jersey",
    "jm": "jamaica",
    "jo": "jordan",
    "jp": "japan",
    "ke": "kenya",
    "kg": "kyrgyzstan",
    "kh": "cambodia",
    "ki": "kiribati",
    "km": "comoros",
    "kn": "saint-kitts-and-nevis",
    "kp": "north-korea",
    "kr": "south-korea",
    "kw": "kuwait",
    "ky": "cayman-islands",
    "kz": "kazakhstan",
    "la": "laos",
    "lb": "lebanon",
    "lc": "saint-lucia",
    "li": "liechtenstein",
    "lk": "sri-lanka",
    "lr": "liberia",
    "ls": "lesotho",
    "lt": "lithuania",
    "lu": "luxembourg",
    "lv": "latvia",
    "ly": "libya",
    "ma": "morocco",
    "mc": "monaco",
    "md": "moldova",
    "me": "montenegro",
    "mf": "saint-martin",
    "mg": "madagascar",
    "mh": "marshall-islands",
    "mk": "north-macedonia",
    "ml": "mali",
    "mm": "myanmar",
    "mn": "mongolia",
    "mo": "macau",
    "mp": "northern-mariana-islands",
    "mq": "martinique",
    "mr": "mauritania",
    "ms": "montserrat",
    "mt": "malta",
    "mu": "mauritius",
    "mv": "maldives",
    "mw": "malawi",
    "mx": "mexico",
    "my": "malaysia",
    "mz": "mozambique",
    "na": "namibia",
    "nc": "new-caledonia",
    "ne": "niger",
    "nf": "norfolk-island",
    "ng": "nigeria",
    "ni": "nicaragua",
    "nl": "netherlands",
    "no": "norway",
    "np": "nepal",
    "nr": "nauru",
    "nu": "niue",
    "nz": "new-zealand",
    "om": "oman",
    "pa": "panama",
    "pe": "peru",
    "pf": "french-polynesia",
    "pg": "papua-new-guinea",
    "ph": "philippines",
    "pk": "pakistan",
    "pl": "poland",
    "pm": "saint-pierre-and-miquelon",
    "pn": "pitcairn-islands",
    "pr": "puerto-rico",
    "ps": "palestine",
    "pt": "portugal",
    "pw": "palau",
    "py": "paraguay",
    "qa": "qatar",
    "re": "reunion",
    "ro": "romania",
    "rs": "serbia",
    "ru": "russia",
    "rw": "rwanda",
    "sa": "saudi-arabia",
    "sb": "solomon-islands",
    "sc": "seychelles",
    "sd": "sudan",
    "se": "sweden",
    "sg": "singapore",
    "sh": "saint-helena",
    "si": "slovenia",
    "sj": "svalbard",
    "sk": "slovakia",
    "sl": "sierra-leone",
    "sm": "san-marino",
    "sn": "senegal",
    "so": "somalia",
    "sr": "suriname",
    "ss": "south-sudan",
    "st": "sao-tome-and-principe",
    "sv": "el-salvador",
    "sx": "sint-maarten",
    "sy": "syria",
    "sz": "eswatini",
    "tc": "turks-and-caicos",
    "td": "chad",
    "tf": "french-southern-territories",
    "tg": "togo",
    "th": "thailand",
    "tj": "tajikistan",
    "tk": "tokelau",
    "tl": "east-timor",
    "tm": "turkmenistan",
    "tn": "tunisia",
    "to": "tonga",
    "tr": "turkey",
    "tt": "trinidad-and-tobago",
    "tv": "tuvalu",
    "tw": "taiwan",
    "tz": "tanzania",
    "ua": "ukraine",
    "ug": "uganda",
    "us": "united-states",
    "uy": "uruguay",
    "uz": "uzbekistan",
    "va": "vatican-city",
    "vc": "saint-vincent-and-the-grenadines",
    "ve": "venezuela",
    "vg": "virgin-islands",
    "vi": "u.s.-virgin-islands",
    "vn": "vietnam",
    "vu": "vanuatu",
    "wf": "wallis-and-futuna",
    "ws": "samoa",
    "xk": "kosovo",
    "ye": "yemen",
    "yt": "mayotte",
    "za": "south-africa",
    "zm": "zambia",
    "zw": "zimbabwe"
};

const filename = window.location.href.split('/').slice(-1)[0].split('.')[0];

// write a script in JavaScript that finds every instance of the character 🇺🇸 
// on a web page and replaces it with a link to "america.html"
// Update the script to work with any flag emoji
function replaceFlagsWithLinks() {
    // Regional Indicator Symbol range: U+1F1E6 to U+1F1FF
    const flagPattern = /([\uD83C][\uDDE6-\uDDFF])([\uD83C][\uDDE6-\uDDFF])/g;

    const newContent = document.body.innerHTML.replace(flagPattern, function(match, p1, p2) {
        // Extract the country code from the matched flag, for example: "US" for 🇺🇸
        const countryCode = String.fromCodePoint(p1.codePointAt(0) - 0x1F1E6 + 'A'.codePointAt(0))
                          + String.fromCodePoint(p2.codePointAt(0) - 0x1F1E6 + 'A'.codePointAt(0));
      
        return `<a href="countries/${countryCodes[countryCode.toLowerCase()] || 'united-states'}.html#${filename}">${match}</a>`;
    });
  
    document.body.innerHTML = newContent;
}

document.addEventListener('DOMContentLoaded', function() {
    replaceFlagsWithLinks();
});