// imagine/config.js
// Static configuration for the imagine frontend.

const API_BASE = "https://api.andrewzc.net";
const IMAGE_BASE = "https://images.andrewzc.net";

// Model display order — used on image.html to sort images and on index.html
// to pick the best representative image. Earlier entries take priority.
const MODEL_PRIORITY = [
  "gpt", "nano", "seedream", "flux",
  "openai", "getimg", "gemini", "meta",
];

// Category groups shown on the index page. The first group is always shown in full.
// Groups 2 and 3 are sampled randomly to fill the display set.
const categories = [
  [
    { id: "new",      emoji: "💭" },
  ],
  [
    { id: "people",   emoji: "👩🏻‍🤝‍👨🏼" },
    { id: "places",   emoji: "🌎" },
    { id: "things",   emoji: "📦" },
    { id: "activities", emoji: "🎯" },
    { id: "albums",   emoji: "💿" },
    { id: "animals",  emoji: "🐊" },
    { id: "artistic", emoji: "📸" },
    { id: "bathing",  emoji: "🤽‍♂️" },
    { id: "buildings",emoji: "🏛️" },
    { id: "africa",   emoji: "🌍" },
    { id: "bodies",   emoji: "🤽‍♂️" },
    { id: "boys",     emoji: "👦🏻" },
    { id: "cars",     emoji: "🚗" },
    { id: "chaos",    emoji: "💥" },
    { id: "food",     emoji: "🍔" },
    { id: "girls",    emoji: "👩🏻" },
    { id: "japan",    emoji: "🇯🇵" },
    { id: "korea",    emoji: "🇰🇷" },
    { id: "las vegas",emoji: "🎰" },
    { id: "nature",   emoji: "🌿" },
    { id: "new york", emoji: "🇺🇸" },
    { id: "plants",   emoji: "🌺" },
    { id: "real",     emoji: "📸" },
    { id: "russia",   emoji: "🇷🇺" },
    { id: "space",    emoji: "🪐" },
    { id: "subway",   emoji: "🚇" },
    { id: "sports",   emoji: "⚽️" },
    { id: "tech",     emoji: "🤖" },
    { id: "life",     emoji: "✅" },
    { id: "self",     emoji: "🤪" },
    { id: "vintage",  emoji: "📠" },
    { id: "fashion",  emoji: "💃🏻" },
  ],
  [
    { id: "aliens",       emoji: "👽" },
    { id: "alcohol",      emoji: "🍸" },
    { id: "apple",        emoji: "🍏" },
    { id: "art",          emoji: "🖼️" },
    { id: "beaches",      emoji: "🏖️" },
    { id: "belgium",      emoji: "🇧🇪" },
    { id: "birds",        emoji: "🐦" },
    { id: "boats",        emoji: "⛵️" },
    { id: "breakfast",    emoji: "🍳" },
    { id: "buses",        emoji: "🚌" },
    { id: "california",   emoji: "🌴" },
    { id: "canada",       emoji: "🇨🇦" },
    { id: "cats",         emoji: "🐱" },
    { id: "china",        emoji: "🇨🇳" },
    { id: "coffee",       emoji: "☕️" },
    { id: "desert",       emoji: "🏜️" },
    { id: "dogs",         emoji: "🐶" },
    { id: "dresses",      emoji: "👗" },
    { id: "drinks",       emoji: "🍹" },
    { id: "dubai",        emoji: "🇦🇪" },
    { id: "egypt",        emoji: "🇪🇬" },
    { id: "england",      emoji: "🇬🇧" },
    { id: "france",       emoji: "🇫🇷" },
    { id: "frogs",        emoji: "🐸" },
    { id: "games",        emoji: "🎲" },
    { id: "germany",      emoji: "🇩🇪" },
    { id: "hands",        emoji: "🖐️" },
    { id: "holland",      emoji: "🇳🇱" },
    { id: "india",        emoji: "🇮🇳" },
    { id: "italy",        emoji: "🇮🇹" },
    { id: "light",        emoji: "🌅" },
    { id: "marble",       emoji: "🪨" },
    { id: "metro",        emoji: "🚇" },
    { id: "mexico",       emoji: "🇲🇽" },
    { id: "night",        emoji: "🌃" },
    { id: "octopus",      emoji: "🐙" },
    { id: "phones",       emoji: "📱" },
    { id: "pizza",        emoji: "🍕" },
    { id: "planes",       emoji: "✈️" },
    { id: "pools",        emoji: "🏊‍♂️" },
    { id: "rainbows",     emoji: "🌈" },
    { id: "restrooms",    emoji: "🚽" },
    { id: "senegal",      emoji: "🇸🇳" },
    { id: "fan art",      emoji: "🖼️" },
    { id: "sunglasses",   emoji: "😎" },
    { id: "swimsuits",    emoji: "👙" },
    { id: "trains",       emoji: "🚊" },
    { id: "ukraine",      emoji: "🇺🇦" },
    { id: "lipstick",     emoji: "💄" },
    { id: "flowers",      emoji: "💐" },
    { id: "dinosaurs",    emoji: "🦖" },
    { id: "statues",      emoji: "🗿" },
    { id: "bling",        emoji: "🤑" },
    { id: "enby",         emoji: "🧑‍🦳" },
    { id: "fitness",      emoji: "🏋️" },
    { id: "underwear",    emoji: "🩲" },
    { id: "money",        emoji: "💶" },
    { id: "kitchens",     emoji: "⏲️" },
    { id: "red",          emoji: "🔴" },
    { id: "orange",       emoji: "🟠" },
    { id: "yellow",       emoji: "🟡" },
    { id: "green",        emoji: "🟢" },
    { id: "blue",         emoji: "🔵" },
    { id: "purple",       emoji: "🟣" },
    { id: "black",        emoji: "⚫️" },
    { id: "white",        emoji: "⚪️" },
    { id: "pink",         emoji: "🩷" },
    { id: "turquoise",    emoji: "👗" },
  ],
];

// Hyphenation hints for long prompt names displayed in text tiles.
const hyphenations = {
  "Rollerblades":  "Roller- blades",
  "Strawberries":  "Straw- berries",
  "Whack-a-Mole":  "Whack- a-Mole",
  "Cosmopolitan":  "Cosmo- politan",
  "VelociPastor":  "Veloci- Pastor",
  "Blueberries":   "Blue- berries",
  "Fluorescent":   "Fluor- escent",
  "Brownstones":   "Brown- stones",
  "Chimichanga":   "Chimi- changa",
  "Cranberries":   "Cran- berries",
  "Lamborghini":   "Lambor- ghini",
  "Magnificent":   "Magni- ficent",
  "Marshmallow":   "Marsh- mallow",
  "Routemaster":   "Route- master",
  "Skateosaurs":   "Skate- osaurs",
  "Rattlesnake":   "Rattle- snake",
  "Motorcycle":    "Motor- cycle",
  "Revolution":    "Revo- lution",
  "Shinkansen":    "Shinkan- sen",
  "Strawberry":    "Straw- berry",
  "Sunflowers":    "Sun-<br>flowers",
  "Tapdancing":    "Tap- dancing",
  "Volkswagen":    "Volks- wagen",
  "Watermelon":    "Water- melon",
  "Pineapple":     "Pine- apple",
  "Mannequin":     "Manne- quin",
  "Microwave":     "Micro- wave",
  "Hamburger":     "Ham- burger",
  "Colosseum":     "Colos- seum",
};
