// animals/config.js
// Static animal data for the animals frontend.
// Artist/style config comes from GET /animals/artists.

const IMAGE_BASE = "https://images.andrewzc.net";
const API_BASE   = "https://api.andrewzc.net";

const animals = [
  ["🐒", "Monkey"],
  ["🦍", "Gorilla"],
  ["🦧", "Orangutan"],
  ["🐕", "Dog"],
  ["🐩", "Poodle"],
  ["🐺", "Wolf"],
  ["🦊", "Fox"],
  ["🦝", "Raccoon"],
  ["🐈", "Cat"],
  ["🦁", "Lion"],
  ["🐅", "Tiger"],
  ["🐆", "Leopard"],
  ["🐎", "Horse"],
  ["🦄", "Unicorn"],
  ["🦌", "Gazelle"],
  ["🦓", "Zebra"],
  ["🫏", "Donkey"],
  ["🐂", "Ox"],
  ["🐃", "Water Buffalo"],
  ["🐄", "Cow"],
  ["🐖", "Pig"],
  ["🐗", "Boar"],
  ["🐏", "Ram"],
  ["🐐", "Goat"],
  ["🐪", "Camel"],
  ["🦙", "Llama"],
  ["🦒", "Giraffe"],
  ["🐘", "Elephant"],
  ["🦣", "Mammoth"],
  ["🦏", "Rhinoceros"],
  ["🦛", "Hippopotamus"],
  ["🐁", "Mouse"],
  ["🐀", "Rat"],
  ["🐹", "Hamster"],
  ["🐇", "Rabbit"],
  ["🐿️", "Chipmunk"],
  ["🦫", "Beaver"],
  ["🦔", "Hedgehog"],
  ["🦇", "Bat"],
  ["🐻", "Bear"],
  ["🐻‍❄️", "Polar Bear"],
  ["🐨", "Koala"],
  ["🐼", "Panda"],
  ["🦥", "Sloth"],
  ["🦦", "Otter"],
  ["🦨", "Skunk"],
  ["🦘", "Kangaroo"],
  ["🦡", "Badger"],
  ["🦃", "Turkey"],
  ["🐔", "Chicken"],
  ["🐦", "Crow"],
  ["🐧", "Penguin"],
  ["🕊️", "Dove"],
  ["🦅", "Eagle"],
  ["🦆", "Duck"],
  ["🦢", "Swan"],
  ["🦉", "Owl"],
  ["🦤", "Dodo"],
  ["🪿", "Goose"],
  ["🐸", "Frog"],
  ["🐊", "Crocodile"],
  ["🐢", "Turtle"],
  ["🦎", "Lizard"],
  ["🐍", "Snake"],
  ["🐉", "Dragon"],
  ["🦖", "Dinosaur"],
  ["🐳", "Whale"],
  ["🐬", "Dolphin"],
  ["🐟", "Fish"],
  ["🐡", "Blowfish"],
  ["🦈", "Shark"],
  ["🐙", "Octopus"],
  ["🐌", "Snail"],
  ["🐛", "Caterpillar"],
  ["🐜", "Ant"],
  ["🐝", "Bee"],
  ["🪲", "Beetle"],
  ["🐞", "Ladybug"],
  ["🦋", "Butterfly"],
  ["🪳", "Cockroach"],
  ["🪰", "Fly"],
  ["🦗", "Cricket"],
  ["🕷️", "Spider"],
  ["🦂", "Scorpion"],
  ["🦟", "Mosquito"],
].sort((a, b) => a[1].localeCompare(b[1]));

const shortAnimals = [
  ["🐇", "Rabbit"],
  ["🐈", "Cat"],
  ["🐉", "Dragon"],
  ["🐊", "Crocodile"],
  ["🐍", "Snake"],
  ["🐒", "Monkey"],
  ["🐕", "Dog"],
  ["🐙", "Octopus"],
  ["🐜", "Ant"],
  ["🐡", "Blowfish"],
  ["🐪", "Camel"],
  ["🕷️", "Spider"],
  ["🦂", "Scorpion"],
  ["🦄", "Unicorn"],
  ["🦆", "Duck"],
  ["🦎", "Lizard"],
  ["🦓", "Zebra"],
  ["🦙", "Llama"],
  ["🦫", "Beaver"],
  ["🦥", "Sloth"],
].sort((a, b) => a[1].localeCompare(b[1]));

// Display name overrides for long animal names shown in text tiles.
const hyphenations = {
  "Caterpillar":   "Cater- pillar",
  "Hippopotamus":  "Hippo- potamus",
  "Rhinoceros":    "Rhino- ceros",
  "Crocodile":     "Croco- dile",
};
